---
- name: Linux Production Hardening
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Ensure variables are loaded when using tags
      include_vars: ../group_vars/all.yml

  roles:
    - users
    - ssh
    - firewall
    - packages
    - selinux
    - sysctl

